name: Brand Recommender

on:
  schedule:
    # Runs every Monday at 9:00 AM UTC (adjust timezone as needed)
    - cron: '0 9 * * 1'
  
  # Allows manual triggering from GitHub Actions tab
  workflow_dispatch:

jobs:
  recommend-brands:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run brand recommender
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        run: python brand_recommender_github.py
      
      - name: Upload results as artifacts
        uses: actions/upload-artifact@v4
        if: always()  # Upload even if there are errors
        with:
          name: brand-recommendations-${{ github.run_number }}
          path: brand_recommendations/
          retention-days: 30
      
      - name: Create release with results (optional)
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          tag_name: results-${{ github.run_number }}
          name: Brand Recommendations - ${{ github.run_number }}
          files: brand_recommendations/*
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
